- hosts: downloaders
  tasks:
    - name: Install epel
      dnf:
        name:
          - epel-release
        state: latest
    - name: Install aria2 and tmux
      dnf:
        name:
          - aria2
          - tmux
        state: latest
  vars:
    packages_host:
      tmux:
        version: latest
      aria2:
        version: latest

  remote_user: root
  # roles:
  #   - arillso.repositories
  #   - itigoag.packages
    # - role: linuxhq.yum
    #   yum_install:
    #     - aria2
    #     - tmux
    #   yum_opts:
    #     enablerepo:
    #       - epel
    #   yum_update: true
